# networks:
#   my-network:
#     driver: bridge

# services:
#   my-dotnet:
#     container_name: dotnet-product
#     build:
#       dockerfile: Dockerfile
#       context: .
#     hostname: dotnet
#     restart: always
#     networks:
#       - my-network
#     ports:
#       - "8080:8080"
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Development
#       - ASPNETCORE_URLS=http://+:8080
#     depends_on:
#       - my-sql

#   my-sql:
#     container_name: mysql-product
#     image: mysql:latest
#     hostname: mysql
#     restart: always
#     networks:
#       - my-network
#     volumes:
#       - ./db:/var/lib/mysql
#       - ./db-init:/docker-entrypoint-initdb.d
#     environment:
#       - MYSQL_ROOT_PASSWORD=123abc
#       - MYSQL_DATABASE=SchoolManagement
#       - MYSQL_USER=siteuser
#       - MYSQL_PASSWORD=sitepass
networks:
  my-network:
    name: school-management-net
    driver: bridge
services:
  my-dotnet:
    container_name: dotnet-product
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    networks:
      - my-network
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=server=my-sql;port=3306;database=SchoolManagement;user=root;password=123abc
    depends_on:
      my-sql:
        condition: service_healthy

  my-sql:
    container_name: mysql-product
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    networks:
      - my-network
    volumes:
      # - ./db:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=123abc
      - MYSQL_DATABASE=SchoolManagement
      # - MYSQL_USER=siteuser
      # - MYSQL_PASSWORD=sitepass
    healthcheck:
      # test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123abc"]
      interval: 10s
      timeout: 5s
      retries: 5
